### ISSUE TITLE
放开限流限制后，连续通过apikey发送20多个消息后，提示报错

### ISSUE THREAD

**Issue by sygaton** [hncboy/chatgpt-web-java#25]
[问题描述]放开限流限制后，连续通过apikey发送20多个消息后，提示报错，报错信息如下：
```bash
2023-04-04 19:43:01.886  WARN 23814 --- [.openai.com/...] c.h.c.f.a.l.ParsedEventSourceListener    : 消息发送异常，当前已接收消息：，响应内容：{
 "error": {
    "message": "This model's maximum context length is 4097 tokens. However, you requested 4283 tokens (3283 in the messages, 1000 in the completion). Please reduce the length of the messages or completion.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
}
，异常堆栈：
Exception in thread "OkHttp Dispatcher" java.lang.IllegalArgumentException: argument "content" is null
        at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4829)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3596)
        at com.hncboy.chatgpt.base.util.ObjectMapperUtil.fromJson(ObjectMapperUtil.java:44)
        at com.hncboy.chatgpt.front.api.parser.ChatCompletionResponseParser.parseSuccess(ChatCompletionResponseParser.java:23)
        at com.hncboy.chatgpt.front.api.parser.ChatCompletionResponseParser.parseSuccess(ChatCompletionResponseParser.java:18)
        at com.hncboy.chatgpt.front.api.storage.ApiKeyDatabaseDataStorage.populateMessageUsageToken(ApiKeyDatabaseDataStorage.java:44)
        at com.hncboy.chatgpt.front.api.storage.ApiKeyDatabaseDataStorage.onErrorMessage(ApiKeyDatabaseDataStorage.java:34)
        at com.hncboy.chatgpt.front.api.storage.AbstractDatabaseDataStorage.onError(AbstractDatabaseDataStorage.java:121)
        at com.hncboy.chatgpt.front.api.listener.ParsedEventSourceListener.onFailure(ParsedEventSourceListener.java:167)
        at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:52)
        at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
### 后续再次发送消息时，则所有消息都是返回Request failed with status code 504，后台的错误信息如下：
```bash
2023-04-04 19:47:49.232 ERROR 23814 --- [nio-8699-exec-6] c.h.c.f.service.impl.ChatServiceImpl     : 请求参数：{"prompt":"你是谁？","options":{"conversationId":"e41f46e7-b05e-4dc4-a47e-25160817d265","parentMessageId":"9bfed09b-db52-4c71-9100-ed815139b153"},"systemMessage":null}，Back-end closed the emitter connection.
2023-04-04 19:47:49.244 ERROR 23814 --- [nio-8699-exec-6] c.h.c.b.e.RestExceptionTranslator        : 服务器异常

org.springframework.web.context.request.async.AsyncRequestTimeoutException: null
        at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42) ~[spring-web-5.3.26.jar!/:5.3.26]
        at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79) ~[spring-web-5.3.26.jar!/:5.3.26]
        at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438) ~[spring-web-5.3.26.jar!/:5.3.26]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
        at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151) ~[spring-web-5.3.26.jar!/:5.3.26]
        at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44) ~[tomcat-embed-core-9.0.73.jar!/:na]
        at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:133) ~[tomcat-embed-core-9.0.73.jar!/:na]
        at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:137) ~[tomcat-embed-core-9.0.73.jar!/:na]
        at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:240) ~[tomcat-embed-core-9.0.73.jar!/:na]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:57) ~[tomcat-embed-core-9.0.73.jar!/:na]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) ~[tomcat-embed-core-9.0.73.jar!/:na]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) ~[tomcat-embed-core-9.0.73.jar!/:na]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.73.jar!/:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.73.jar!/:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.73.jar!/:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.73.jar!/:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

**Comment by hncboy** [comment]
后续再次发送消息时，则所有消息都是返回Request failed with status code 504

这个是异常，还没做处理。

**Comment by hncboy** [comment]
已优化提示消息
