### ISSUE TITLE
几个偶发问题, 汇总一下

### ISSUE THREAD

**Issue by TSiven** [hncboy/chatgpt-web-java#39]
java.lang.IllegalStateException: ResponseBodyEmitter has already completed
	at org.springframework.util.Assert.state(Assert.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.send(ResponseBodyEmitter.java:196)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.send(ResponseBodyEmitter.java:184)
	at com.hncboy.chatgpt.api.listener.ResponseBodyEmitterStreamListener.onError(ResponseBodyEmitterStreamListener.java:49)
	at com.hncboy.chatgpt.api.listener.ParsedEventSourceListener.onFailure(ParsedEventSourceListener.java:185)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:78)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

---------------------------------------------------------------------------------------------------------

org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:309)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:271)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:118)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at org.springframework.util.StreamUtils.copy(StreamUtils.java:148)
	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:126)
	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:44)
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$HttpMessageConvertingHandler.sendInternal(ResponseBodyEmitterReturnValueHandler.java:212)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$HttpMessageConvertingHandler.send(ResponseBodyEmitterReturnValueHandler.java:205)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.sendInternal(ResponseBodyEmitter.java:204)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.send(ResponseBodyEmitter.java:198)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.send(ResponseBodyEmitter.java:184)
	at com.hncboy.chatgpt.api.listener.ResponseBodyEmitterStreamListener.onMessage(ResponseBodyEmitterStreamListener.java:33)
	at com.hncboy.chatgpt.api.listener.ParsedEventSourceListener.onEvent(ParsedEventSourceListener.java:156)
	at okhttp3.internal.sse.RealEventSource.onEvent(RealEventSource.kt:101)
	at okhttp3.internal.sse.ServerSentEventReader.completeEvent(ServerSentEventReader.kt:108)
	at okhttp3.internal.sse.ServerSentEventReader.processNextEvent(ServerSentEventReader.kt:52)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:75)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by TSiven** [comment]
再补充一个异常信息

okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:355) at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276) at okio.RealBufferedSource.select(RealBufferedSource.kt:229) at okhttp3.internal.sse.ServerSentEventReader.processNextEvent(ServerSentEventReader.kt:50) at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:75) at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46) at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

**Comment by mornone** [comment]
`2023-04-11T10:28:01.251+08:00  WARN 30387 --- [nio-3002-exec-4] c.h.c.base.handler.SensitiveWordHandler  : 开始构建敏感词树
2023-04-11T10:28:01.318+08:00  WARN 30387 --- [nio-3002-exec-4] c.h.c.base.handler.SensitiveWordHandler  : 查询数据库，敏感词数量为：1061 个
2023-04-11T10:28:02.438+08:00  WARN 30387 --- [.openai.com/...] c.h.c.f.a.l.ParsedEventSourceListener    : 消息发送异常，当前已接收消息：，响应内容：{
  "error": {
    "message": "Invalid URL (POST /}v1/chat/completions)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
，异常堆栈：
Exception in thread "OkHttp Dispatcher" java.lang.IllegalArgumentException: argument "content" is null
        at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4885)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3644)
        at com.hncboy.chatgpt.base.util.ObjectMapperUtil.fromJson(ObjectMapperUtil.java:44)
        at com.hncboy.chatgpt.front.api.parser.ChatCompletionResponseParser.parseSuccess(ChatCompletionResponseParser.java:23)
        at com.hncboy.chatgpt.front.api.parser.ChatCompletionResponseParser.parseSuccess(ChatCompletionResponseParser.java:18)
        at com.hncboy.chatgpt.front.api.storage.ApiKeyDatabaseDataStorage.populateMessageUsageToken(ApiKeyDatabaseDataStorage.java:44)
        at com.hncboy.chatgpt.front.api.storage.ApiKeyDatabaseDataStorage.onErrorMessage(ApiKeyDatabaseDataStorage.java:34)
        at com.hncboy.chatgpt.front.api.storage.AbstractDatabaseDataStorage.onError(AbstractDatabaseDataStorage.java:121)
        at com.hncboy.chatgpt.front.api.listener.ParsedEventSourceListener.onFailure(ParsedEventSourceListener.java:167)
        at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:52)
        at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
/`

数据库中已经有了数据，idea中运行测试没问题，打jar包上传服务器运行报这个错误，前端界面能正常访问输入。

**Comment by hncboy** [comment]
> 

application-pord.yml 有问题，最新版本修复。

**Comment by hncboy** [comment]
> `2023-04-11T10:28:01.251+08:00 WARN 30387 --- [nio-3002-exec-4] c.h.c.base.handler.SensitiveWordHandler : 开始构建敏感词树 2023-04-11T10:28:01.318+08:00 WARN 30387 --- [nio-3002-exec-4] c.h.c.base.handler.SensitiveWordHandler : 查询数据库，敏感词数量为：1061 个 2023-04-11T10:28:02.438+08:00 WARN 30387 --- [.openai.com/...] c.h.c.f.a.l.ParsedEventSourceListener : 消息发送异常，当前已接收消息：，响应内容：{ "error": { "message": "Invalid URL (POST /}v1/chat/completions)", "type": "invalid_request_error", "param": null, "code": null } } ，异常堆栈： Exception in thread "OkHttp Dispatcher" java.lang.IllegalArgumentException: argument "content" is null at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4885) at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3644) at com.hncboy.chatgpt.base.util.ObjectMapperUtil.fromJson(ObjectMapperUtil.java:44) at com.hncboy.chatgpt.front.api.parser.ChatCompletionResponseParser.parseSuccess(ChatCompletionResponseParser.java:23) at com.hncboy.chatgpt.front.api.parser.ChatCompletionResponseParser.parseSuccess(ChatCompletionResponseParser.java:18) at com.hncboy.chatgpt.front.api.storage.ApiKeyDatabaseDataStorage.populateMessageUsageToken(ApiKeyDatabaseDataStorage.java:44) at com.hncboy.chatgpt.front.api.storage.ApiKeyDatabaseDataStorage.onErrorMessage(ApiKeyDatabaseDataStorage.java:34) at com.hncboy.chatgpt.front.api.storage.AbstractDatabaseDataStorage.onError(AbstractDatabaseDataStorage.java:121) at com.hncboy.chatgpt.front.api.listener.ParsedEventSourceListener.onFailure(ParsedEventSourceListener.java:167) at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:52) at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46) at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) at java.base/java.lang.Thread.run(Thread.java:833) /`
> 
> 数据库中已正常记录消息数据 *************************** 4. row *************************** id: 1645614650504531970 message_id: 5130ec3b-8667-4b53-9b4a-a5b23de87ec6 parent_message_id: NULL parent_answer_message_id: NULL parent_question_message_id: NULL context_count: 1 question_context_count: 1 message_type: 1 chat_room_id: 1645614650504531971 conversation_id: NULL api_type: ApiKey api_key: xxx content: test original_data: {"model":"gpt-3.5-turbo","messages":[{"role":"system","content":"You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully. Respond using markdown."},{"role":"user","content":"test"}],"temperature":0.8,"n":1,"stream":true,"top_p":1.0,"max_tokens":1000,"presence_penalty":1.0,"frequency_penalty":0.0} response_error_data: { "error": { "message": "Invalid URL (POST /}v1/chat/completions)", "type": "invalid_request_error", "param": null, "code": null } }
> 
> ```
>          prompt_tokens: -1
>      completion_tokens: -1
>           total_tokens: -1
>                     ip: 144.202.48.47
>                 status: 3
>                is_hide: 0
>            create_time: 2023-04-11 10:28:01
>            update_time: 2023-04-11 10:28:02
> ```
> 
> 数据库中已经有了数据，idea中运行测试没问题，打jar包上传服务器运行报这个错误，前端界面能正常访问输入。

application-pord.yml 有问题，最新版本已修复。
