### ISSUE TITLE
cn.hutool.crypto.CryptoException: SecurityException: JCE cannot authenticate the provider BC

### ISSUE THREAD

**Issue by sunjujava** [hncboy/chatgpt-web-java#53]
windows下面正常，发布到CentOS 8.5.2111之后登录接口就报错。
最后没办法在项目启动的时候SecureUtil.disableBouncyCastle()禁用了BouncyCastle临时解决了，大家有没有碰到过，有没有更好的解决办法？

JAVA版本如下：
java version "17.0.7" 2023-04-18 LTS
Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.7+8-LTS-224, mixed mode, sharing)

错误信息如下：
cn.hutool.crypto.CryptoException: SecurityException: JCE cannot authenticate the provider BC
        at cn.hutool.crypto.digest.mac.DefaultHMacEngine.init(DefaultHMacEngine.java:105) ~[hutool-all-5.8.18.jar!/:5.8.18]
        at cn.hutool.crypto.digest.mac.DefaultHMacEngine.<init>(DefaultHMacEngine.java:56) ~[hutool-all-5.8.18.jar!/:5.8.18]
        at cn.hutool.crypto.digest.mac.MacEngineFactory.createEngine(MacEngineFactory.java:42) ~[hutool-all-5.8.18.jar!/:5.8.18]
        at cn.hutool.crypto.digest.HMac.<init>(HMac.java:86) ~[hutool-all-5.8.18.jar!/:5.8.18]
        at cn.hutool.crypto.digest.HMac.<init>(HMac.java:74) ~[hutool-all-5.8.18.jar!/:5.8.18]
        at cn.hutool.crypto.digest.HMac.<init>(HMac.java:63) ~[hutool-all-5.8.18.jar!/:5.8.18]
        at cn.hutool.jwt.signers.HMacJWTSigner.<init>(HMacJWTSigner.java:28) ~[hutool-all-5.8.18.jar!/:5.8.18]
        at cn.hutool.jwt.signers.JWTSignerUtil.createSigner(JWTSignerUtil.java:239) ~[hutool-all-5.8.18.jar!/:5.8.18]
        at cn.hutool.jwt.signers.JWTSignerUtil.hs256(JWTSignerUtil.java:36) ~[hutool-all-5.8.18.jar!/:5.8.18]
        at cn.hutool.jwt.JWT.setKey(JWT.java:126) ~[hutool-all-5.8.18.jar!/:5.8.18]
        at cn.dev33.satoken.jwt.SaJwtTemplate.generateToken(SaJwtTemplate.java:119) ~[sa-token-jwt-1.34.0.jar!/:?]
        at cn.dev33.satoken.jwt.SaJwtTemplate.createToken(SaJwtTemplate.java:109) ~[sa-token-jwt-1.34.0.jar!/:?]
        at cn.dev33.satoken.jwt.SaJwtUtil.createToken(SaJwtUtil.java:100) ~[sa-token-jwt-1.34.0.jar!/:?]
        at cn.dev33.satoken.jwt.StpLogicJwtForStateless.createTokenValue(StpLogicJwtForStateless.java:60) ~[sa-token-jwt-1.34.0.jar!/:?]
        at cn.dev33.satoken.jwt.StpLogicJwtForStateless.createLoginSession(StpLogicJwtForStateless.java:99) ~[sa-token-jwt-1.34.0.jar!/:?]
        at cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:331) ~[sa-token-core-1.34.0.jar!/:?]
        at cn.dev33.satoken.stp.StpUtil.login(StpUtil.java:174) ~[sa-token-core-1.34.0.jar!/:?]
        at com.hncboy.chatgpt.front.service.strategy.user.EmailAbstractRegisterStrategy.login(EmailAbstractRegisterStrategy.java:177) ~[classes!/:0.0.1-SNAPSHOT]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

**Comment by kamisangk** [comment]
我更换OpenJDK 17.0.7后正常了
