### ISSUE TITLE
请问下， 改为科学上网端口后，出现java.io.IOException: unexpected end of stream on... 是哪里出了问题了吗

### ISSUE THREAD

**Issue by heisexiong** [hncboy/chatgpt-web-java#6]
java.lang.RuntimeException: java.io.IOException: unexpected end of stream on **https://api.openai.com/...**
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46) ~[rxjava-2.2.21.jar:na]
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93) ~[rxjava-2.2.21.jar:na]
	at io.reactivex.Single.blockingGet(Single.java:2870) ~[rxjava-2.2.21.jar:na]
	at com.unfbx.chatgpt.OpenAiClient.creditGrants(OpenAiClient.java:845) ~[chatgpt-java-1.0.7.jar:na]
	at com.hncboy.chatgpt.front.service.impl.ChatServiceImpl.getChatConfig(**ChatServiceImpl**.java:37) ~[classes/:na]
	at com.hncboy.chatgpt.front.controller.ChatController.chatConfig(**ChatController**.java:38) ~[classes/:na]
	at com.hncboy.chatgpt.front.controller.ChatController$$FastClassBySpringCGLIB$$f1911854.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.26.jar:5.3.26]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.26.jar:5.3.26]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.26.jar:5.3.26]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.26.jar:5.3.26]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.26.jar:5.3.26]
	at com.hncboy.chatgpt.base.handler.aspect.PreAuthAspect.checkAuth(PreAuthAspect.java:46) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]

**Comment by hncboy** [comment]
是直接进入 onError 方法吗

**Comment by heisexiong** [comment]
是直接访问http://localhost:3002/config接口，然后在ChatServiceImpl的getChatConfig方法中，执行ApiKeyChatClientBuilder.buildOpenAiClient().creditGrants()报的错， 我是把http_proxy_host和http_proxy_port改成了科学上网地址和端口

**Comment by hncboy** [comment]
本地起代理服务器的话 http_proxy_host 127.0.0.1 不用改，只用改 http_proxy_port 就行。我都是直接通的，还没遇到过报错的情况。你的科学上网代理是本机启动的吗。

**Comment by heisexiong** [comment]
我试过不改host，不得，那估计是科学上网的问题了， 不是本机启动的，通过外网服务器代理的

**Comment by hncboy** [comment]
这种情况我还没测试过。如果可以的话，可以私发下你的代理地址。

**Comment by heisexiong** [comment]
我邮件发你了，感谢作者的帮助。

**Comment by hncboy** [comment]
已解决。

**Comment by shizhanghongchen** [comment]
我的问题与 @heisexiong 一样，来一张截图如下：
<img width="1166" alt="image" src="https://github.com/hncboy/chatgpt-web-java/assets/28671142/13e0ec08-9df5-4bdf-a7af-296717b7d050">
我的配置如下：
1. nginx配置
```
server{
    listen 80;
    server_name 127.0.0.1;
    index index.html;
    proxy_buffering off;
    root /opt/software/front/www/dist;
    location /api/ {
        proxy_pass http://localhost:3002/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        add_header X-Cache $upstream_cache_status;
    }
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README.md) {
        return 404;
    }
}
```
```
server{
    listen 8080;
    server_name 127.0.0.1;
    index index.html;
    root /opt/software/front/admin/dist;
    location /api/ {
        proxy_pass http://localhost:3002/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        add_header X-Cache $upstream_cache_status;
    }
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README.md) {
        return 404;
    }
}
```
2. 服务器是国内阿里云
3. 在服务器上使用docker安装clash
4. 将代理ip写入代码配置文件
5. 发送聊天消息就开始报错
6. 我尝试了很多方法都不行？是不是哪里有什么问题？
辛苦大佬指点一二
