### ISSUE TITLE
消息发送异常，当前已接收消息：，响应内容：null，异常堆栈：

### ISSUE THREAD

**Issue by zlxasn** [hncboy/chatgpt-web-java#84]
2023-06-16T17:36:37.285+08:00  WARN 16708 --- [.openai.com/...] c.h.c.f.a.l.ParsedEventSourceListener    : 消息发送异常，当前已接收消息：，响应内容：null，异常堆栈：

java.io.IOException: Unexpected response code for CONNECT: 501
	at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.kt:483) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:262) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:201) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:na]
	at com.unfbx.chatgpt.interceptor.HeaderAuthorizationInterceptor.intercept(HeaderAuthorizationInterceptor.java:51) ~[chatgpt-java-1.0.11.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517) ~[okhttp-4.10.0.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

**Comment by zlxasn** [comment]
调用的发送消息接口，chat_message/send

**Comment by hncboy** [comment]
没遇到过你这个错误，确认下配置是否都填写正确。
