### ISSUE TITLE
配置域名后发送消息：java.io.EOFException: SSL peer shut down incorrectly

### ISSUE THREAD

**Issue by shizhanghongchen** [hncboy/chatgpt-web-java#90]
配置域名后发送消息时报错，不配置域名一切正常
详细错误日志如下：

    javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
            at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1715)
            at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1514)
            at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
            at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
            at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
            at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
            at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
            at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
            at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
            at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
            at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
            at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
            at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at com.unfbx.chatgpt.interceptor.HeaderAuthorizationInterceptor.intercept(HeaderAuthorizationInterceptor.java:51)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
            at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
            at java.base/java.lang.Thread.run(Thread.java:833)
    Caused by: java.io.EOFException: SSL peer shut down incorrectly
            at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489)
            at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478)
            at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
            at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
            at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
            ... 25 common frames omitted

nginx.conf配置

    server{
    listen 80;
    server_name xxxxxx;
    index index.html;
    proxy_buffering off;
    
    proxy_send_timeout 180s;
    proxy_read_timeout 180s;
    
    location / {
            root /opt/software/front/www/dist;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
    }
    
    location /api/ {
            proxy_pass http://localhost:3002/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
    }
    
    location ~ ^/(.user.ini|.htaccess|.git|.env|.svn|.project|LICENSE|README.md) {
           return 404;
    }
    }

有没有知道的大佬辛苦指点一下，小弟万分感谢！

**Comment by hncboy** [comment]
参考下字段填写是否有问题  https://github.com/hncboy/chatgpt-web-java/wiki/%E6%A8%A1%E5%BC%8F%E5%8F%82%E6%95%B0%E4%BB%8B%E7%BB%8D
