### ISSUE TITLE
提问 ”abc歌曲你会吗“ 会出现 非Web上下文无法获取Request 异常

### ISSUE THREAD

**Issue by xiaoshandegithub** [hncboy/chatgpt-web-java#94]
![image](https://github.com/hncboy/chatgpt-web-java/assets/51507077/759b6d8a-e812-4e6c-8ca4-75db0e62214d)

2023-06-26T17:36:26.052+08:00  WARN 20228 --- [/kajshf.top/...] c.h.c.f.a.l.ParsedEventSourceListener    : 消息发送异常，当前已接收消息：当然，"ABC"是一首非常著名的儿童歌曲。以下是歌词的一部分：

A B C D E F G,
H I J K L M N O P,
Q R S T U V,
W X Y 和 Z.

现在我知道我的 ABC，
下次请你和我一起唱!，响应内容：，异常堆栈：

cn.dev33.satoken.exception.NotWebContextException: 非Web上下文无法获取Request
	at cn.dev33.satoken.spring.SpringMVCUtil.getRequest(SpringMVCUtil.java:28) ~[sa-token-spring-boot3-starter-1.34.0.jar:na]
	at cn.dev33.satoken.spring.SaTokenContextForSpringInJakartaServlet.getStorage(SaTokenContextForSpringInJakartaServlet.java:40) ~[sa-token-spring-boot3-starter-1.34.0.jar:na]
	at cn.dev33.satoken.context.SaHolder.getStorage(SaHolder.java:49) ~[sa-token-core-1.34.0.jar:na]
	at cn.dev33.satoken.stp.StpLogic.isSwitch(StpLogic.java:1967) ~[sa-token-core-1.34.0.jar:na]
	at cn.dev33.satoken.stp.StpLogic.getLoginId(StpLogic.java:667) ~[sa-token-core-1.34.0.jar:na]
	at cn.dev33.satoken.stp.StpUtil.getLoginId(StpUtil.java:297) ~[sa-token-core-1.34.0.jar:na]
	at com.hncboy.chatgpt.front.util.FrontUserUtil.getUserId(FrontUserUtil.java:24) ~[classes/:na]
	at com.hncboy.chatgpt.front.util.FrontUserSettingsUtil.getUserCostSettings(FrontUserSettingsUtil.java:65) ~[classes/:na]
	at com.hncboy.chatgpt.front.api.listener.ParsedEventSourceListener.onEvent(ParsedEventSourceListener.java:110) ~[classes/:na]
	at okhttp3.internal.sse.RealEventSource.onEvent(RealEventSource.kt:101) ~[okhttp-sse-4.10.0.jar:na]
	at okhttp3.internal.sse.ServerSentEventReader.completeEvent(ServerSentEventReader.kt:108) ~[okhttp-sse-4.10.0.jar:na]
	at okhttp3.internal.sse.ServerSentEventReader.processNextEvent(ServerSentEventReader.kt:52) ~[okhttp-sse-4.10.0.jar:na]
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:75) ~[okhttp-sse-4.10.0.jar:na]
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46) ~[okhttp-sse-4.10.0.jar:na]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[okhttp-4.10.0.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

**Comment by xiaoshandegithub** [comment]
![image](https://github.com/hncboy/chatgpt-web-java/assets/51507077/92ee8a48-7378-43c4-943c-37de4f93c09f)
